### PR TITLE
user authentication with facebook, google and microsoft

### PR DESCRIPTION
**Pull request by JCarlosHidalgoSosa**
Copy .env file passed via md inside of /pocs/auth/goauth/server directory

### CODE REVIEW

**Review by DeidamiaFuentes — COMMENTED** [review]
image

For all the sign in options I get the same result, could you check it pls?

My bad, something went wrong on my side

**Comment by AngheloZambrana** [comment]
image
When you try to login using discord this screen appears, and cant login with discord.

**Comment by OropezaHugo** [comment]
to me every log in works totally fine

**Review by OropezaHugo — APPROVED** [review]

**Review by MayerliSantander — APPROVED** [review]

**Review by DeidamiaFuentes — APPROVED** [review]
Worked all fine

**Pull request merged**
